### ISSUE TITLE
Bar-gmail is notifying gmail spam mails

### ISSUE THREAD

**Issue by druidamix** [vyachkonovalov/polybar-gmail#35] opened 2023-12-01 11:12 UTC
Hello,

I'm using your plugin. However, it notifies every new spam mail. Seems a bug.

Thanks.

**Comment by crabvk** [comment] 2023-12-01 11:16
That's not a bug, but having a flag like `--no-spam` would be a good feature though.

**Comment by druidamix** [comment] 2023-12-01 14:48
In my opinion, spam mails should be a secondary option, not by default. I receive more spam mails than normal ones. Moreover, they only appear as notifications.

**Comment by crabvk** [comment] 2023-12-01 14:50
I agree.

**Comment by crabvk** [comment] 2023-12-02 09:10
@druidamix
The issue should be fixed now, please check and let me know if it works (because I don't have any new spam messages at the moment).

**Comment by druidamix** [comment] 2023-12-02 16:27
Seems to be working. No spam mails notifications.

Thank you!

**Closed as completed** 2023-12-02 16:28 UTC
